<?php

namespace MugoWeb\Eep\Bundle\Command;

use MugoWeb\Eep\Bundle\Services\EepLogger;
use MugoWeb\Eep\Bundle\Component\Console\Helper\Table;
use Ibexa\Contracts\Core\Repository\LocationService;
use Ibexa\Contracts\Core\Repository\PermissionResolver;
use Ibexa\Contracts\Core\Repository\UserService;
use Ibexa\Contracts\Core\Repository\URLAliasService;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\TableCell;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class EepUrlAliasListLocationCommand extends Command
{
    public function __construct
    (
        URLAliasService $urlAliasService,
        LocationService $locationService,
        PermissionResolver $permissionResolver,
        UserService $userService,
        EepLogger $logger
    )
    {
        $this->urlAliasService = $urlAliasService;
        $this->locationService = $locationService;
        $this->permissionResolver = $permissionResolver;
        $this->userService = $userService;
        $this->logger = $logger;

        parent::__construct();
    }

    protected function configure()
    {
        $help = <<<EOD
TODO

By default, autogenerated/system aliases are listed. Use --custom=1 to list custom aliases.

EOD;

        $this
            ->setName('eep:urlalias:listlocation')
            ->setAliases(array('eep:ua:listlocation'))
            ->setDescription('Lists URL aliases for a location')
            ->addArgument('location-id', InputArgument::REQUIRED, 'Location id')
            ->addOption('custom', null, InputOption::VALUE_OPTIONAL, 'List custom aliases when 1, autogenerated/system aliases when 0', 0)
            ->addOption('language', 'l', InputOption::VALUE_OPTIONAL, 'Language code')
            ->addOption('show-all-translations', null, InputOption::VALUE_NONE, 'Include all aliases as if they were always available')
            ->addOption('prioritized-languages', null, InputOption::VALUE_OPTIONAL, 'Comma-separated prioritized language codes')
            ->addOption('user-id', 'u', InputOption::VALUE_OPTIONAL, 'User id for URL alias operations', 14)
            ->addOption('hide-columns', null, InputOption::VALUE_OPTIONAL, 'CSV of column(s) to hide from results table')
            ->setHelp($help)
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $inputLocationId = $input->getArgument('location-id');
        $inputCustom = (bool) $input->getOption('custom');
        $inputLanguage = $input->getOption('language');
        $inputShowAllTranslations = $input->getOption('show-all-translations');
        $inputPrioritizedLanguages = $input->getOption('prioritized-languages');
        $inputUserId = $input->getOption('user-id');

        $prioritizedLanguages = null;
        if ($inputPrioritizedLanguages)
        {
            $prioritizedLanguages = array_filter(array_map('trim', explode(',', $inputPrioritizedLanguages)));
        }

        $this->permissionResolver->setCurrentUserReference($this->userService->loadUser($inputUserId));

        $location = $this->locationService->loadLocation($inputLocationId);

        $urlAliases = $this->urlAliasService->listLocationAliases
        (
            $location,
            $inputCustom,
            $inputLanguage,
            $inputShowAllTranslations ? true : null,
            $prioritizedLanguages
        );

        $headers = array
        (
            array
            (
                'id',
                'type',
                'destination',
                'path',
                'languageCodes',
                'alwaysAvailable',
                'isHistory',
                'isCustom',
                'forward',
            ),
        );

        $hideColumns = ($input->getOption('hide-columns'))? explode(',', $input->getOption('hide-columns')) : array();
        $headerKeys = array_map(array('MugoWeb\Eep\Bundle\Services\EepUtilities', 'stripColumnMarkers'), $headers[0]);
        foreach($hideColumns as $columnKey)
        {
            $searchResultKey = array_search($columnKey, $headerKeys);
            if($searchResultKey !== false)
            {
                unset($headers[0][$searchResultKey]);
            }
        }

        $rows = array();
        foreach ($urlAliases as $urlAlias)
        {
            $row = array();

            if(!in_array('id', $hideColumns)) { $row[] = $urlAlias->id; }
            if(!in_array('type', $hideColumns)) { $row[] = $urlAlias->type; }
            if(!in_array('destination', $hideColumns)) { $row[] = $urlAlias->destination; }
            if(!in_array('path', $hideColumns)) { $row[] = $urlAlias->path; }
            if(!in_array('languageCodes', $hideColumns)) { $row[] = implode(',', $urlAlias->languageCodes); }
            if(!in_array('alwaysAvailable', $hideColumns)) { $row[] = (integer) $urlAlias->alwaysAvailable; }
            if(!in_array('isHistory', $hideColumns)) { $row[] = (integer) $urlAlias->isHistory; }
            if(!in_array('isCustom', $hideColumns)) { $row[] = (integer) $urlAlias->isCustom; }
            if(!in_array('forward', $hideColumns)) { $row[] = (integer) $urlAlias->forward; }

            $rows[] = $row;
        }

        $resultCount = count($rows);
        $resultSet = ($resultCount)? "1 - " . $resultCount : 0;
        $colWidth = count($headers[0]);

        $infoHeader = array
        (
            new TableCell
            (
                "{$this->getName()} [$inputLocationId]",
                array('colspan' => ($colWidth == 1)? 1 : $colWidth-1)
            ),
            new TableCell
            (
                "Results: $resultSet / $resultCount",
                array('colspan' => 1)
            )
        );
        array_unshift($headers, $infoHeader);

        $io = new SymfonyStyle($input, $output);
        $table = new Table($output);
        $table->setHeaders($headers);
        $table->setRows($rows);
        $table->render();
        $io->newLine();

        return Command::SUCCESS;
    }
}