services:
  _defaults:
    autowire: true
    autoconfigure: true

  MugoWeb\Eep\Bundle\Services\:
    resource: '../src/Services/*'

  MugoWeb\Eep\Bundle\Command\:
    resource: '../src/Command/*'
    tags: ['console.command']

  MugoWeb\Eep\Bundle\Query\Solr\CriterionVisitor\Raw:
    tags:
      - { name: ibexa.search.solr.query.content.criterion.visitor }
      - { name: ibexa.search.solr.query.location.criterion.visitor }

  EzSystems\PlatformHttpCacheBundle\PurgeClient\RepositoryPrefixDecorator:
    alias: ibexa.cache.http.purge_client_decorator
