services:
  _defaults:
    autowire: true
    autoconfigure: true

  MugoWeb\Eep\Bundle\Services\:
    resource: '../src/Services/*'

  MugoWeb\Eep\Bundle\Command\:
    resource: '../src/Command/*'
    tags: ['console.command']

  EzSystems\PlatformHttpCacheBundle\PurgeClient\RepositoryPrefixDecorator:
    alias: ibexa.cache.http.purge_client_decorator